twig:
    default_path: '%kernel.project_dir%/templates'

    # https://symfony.com/doc/current/templating/global_variables.html
    globals:
        categories: '@App\Globals\Categories'
        products : '@App\Globals\Products'
        licence : '@App\Globals\Licences'


when@test:
    twig:
        strict_variables: true
